# Generated by Django 5.1.2 on 2024-11-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecords',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('reg_no', models.CharField(max_length=50, unique=True)),
                ('fee_payment_status', models.CharField(max_length=20)),
                ('exam_performance', models.FloatField()),
                ('reporting_status', models.CharField(max_length=20)),
                ('needs_assistance', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'student_records',
            },
        ),
    ]
